          version: 0.2
          phases:
            install:
              runtime-versions:
                docker: 18
              commands:
                - apt-get -y update
                - apt-get -y install jq
            pre_build:
              commands:
                - echo "Starting docker daemon..."
                - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
                - echo "Logging into Amazon ECR..."
                - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
                - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
                - echo "Installing kubectl"
                - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.2/bin/linux/amd64/kubectl
                - chmod +x ./kubectl
                - mv ./kubectl /usr/local/bin/kubectl
                - export KUBECONFIG=$HOME/.kube/config
                - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
                - helm repo add apache-airflow https://airflow.apache.org
                - aws eks update-kubeconfig --name airflow
            build:
              commands:
                - echo Build started on `date`
                - docker build -t "airflow:latest" .
                - docker tag "airflow:latest" "airflow:latest"
                - echo "Testing..."
                - helm upgrade --install --recreate-pods --wait --timeout 600s --namespace "staging" --set ingress.enabled=true --set ingress.web.path="airflow-staging" --set images.airflow.repository=https://github.com/singhshivam01/airflow-eks-docker --set images.airflow.tag=latest --set executor="KubernetesExecutor" --set env[0].name="AIRFLOW__KUBERNETES__DAGS_IN_IMAGE" --set env[0].value="True" --set env[1].name="AIRFLOW__KUBERNETES__NAMESPACE" --set env[1].value="staging" --set env[2].name="AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY" --set env[2].value=${REPOSITORY_URI} --set env[3].name="AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG" --set env[3].value=${TAG} --set env[4].name="AIRFLOW__KUBERNETES__RUN_AS_USER" --set env[4].value="50000" --set env[5].name="AIRFLOW__API__AUTH_BACKEND" --set env[5].value="airflow.api.auth.backend.default" --set env[6].name="AIRFLOW__WEBSERVER__BASE_URL" --set env[6].value="http://localhost:8080/airflow-staging" airflow-staging airflow-eks-helm-chart/airflow
                - sleep 30s
                - export POD_NAME=$(kubectl get pods --namespace staging -l "component=webserver,release=airflow-staging" -o jsonpath="{.items[0].metadata.name}")
                - kubectl exec $POD_NAME -n staging -- /bin/bash -c "pytest integrationtests"
            post_build:
              commands:
                - echo Build completed on `date`
                - echo "Pushing Docker image to ECR"
                - docker push "airflow:latest"
                - docker push "airflow:latest"
                - printf '{"Tag":"%s","RepositoryUri":"%s"}' $TAG $REPOSITORY_URI $PROJECT_NAME $ARTIFACT_BUCKET > build.json
